version: '3.8'

services:
  agile-backend:
    image: node:18-alpine
    container_name: agile-backend
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://agile_user:agile_password@postgres:5432/agile_db
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npm install && npm run start"
    depends_on:
      - postgres
    networks:
      - default

networks:
  default:
    name: bridge
